version: '3.5'

services:
    php-apache:
        build:
            context: ./php-apache
            args:
                - UID=${UID}
                - GID=${GID}
        environment:
            - http_proxy=${HTTP_PROXY}
            - https_proxy=${HTTPS_PROXY}
            - no_proxy=${NO_PROXY}
        ports: 
            - ${APACHE_PORT}:80
            - ${HOT_RELOAD_PORT}:3000
        volumes:
            - ${PROJECT_PATH}:/var/www
            - ./php-apache/sites:/etc/apache2/sites-available
        depends_on:
            - postgres
            - redis
            - selenium

    postgres:
        image: postgres:9.6-alpine
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        image: redis:3.2.6-alpine
        volumes:
            - redis-data:/data  
        ports:
            - ${REDIS_PORT}:6379

    selenium:
        image: selenium/standalone-firefox
        volumes:
            - ${PROJECT_PATH}:/var/www

volumes:
    postgres-data:
    redis-data:
