version: '3.5'

services:
    web:
        build:
            context: ./web
            args:
                - PHP_VERSION=${PHP_VERSION}
                - NODE_VERSION=${NODE_VERSION} 
        ports: 
            - ${APACHE_PORT}:80
            - ${FRONTEND_PORT}:3000  
        volumes:
            - ${PROJECT_PATH}:/var/www
            - ./web/sites:/etc/apache2/sites-available

    postgres:
        build:
            context: ./postgres
            args: 
                - POSTGRES_VERSION=${POSTGRES_VERSION}
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        depends_on:
            - web

    redis:
        build: 
            context: ./redis
            args: 
                - REDIS_VERSION=${REDIS_VERSION}        
        ports:
            - ${REDIS_PORT}:6379
        depends_on:
            - web
